# Variable Group 'akv' was defined in the Variables tab
trigger:
  branches:
    include:
    - main
resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Job_3
  displayName: SonarCloudcheck
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
  - task: SonarCloudPrepare@1
    displayName: Prepare analysis on SonarCloud
    enabled: False
    inputs:
      SonarCloud: c0b658a3-da5a-43eb-a549-86be87232e6f
      organization: epam-diploma-v7
      scannerMode: CLI
      configMode: manual
      cliProjectKey: sark0205_epam-diploma-v7
      projectKey: dev-epam-diploma-v7
      cliProjectName: epam-diploma-v7
      projectName: dev-epam-diploma-v7
  - task: SonarCloudAnalyze@1
    displayName: Run Code Analysis
    enabled: False
  - task: SonarCloudPublish@1
    displayName: Publish Quality Gate Result
    enabled: False
- job: Job_1
  displayName: build and upload docker
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
  - task: Docker@2
    displayName: buildAndPush
    inputs:
      containerRegistry: fd67483c-8e04-4020-aa06-623b6a6f9460
      repository: rinxster
      tags: >-
        $(Build.BuildId)

        latest
- job: Job_2
  displayName: upload artefacts
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true

  - task: replacetokens@4
    displayName: Replace tokens in **/*.yaml
    inputs:
      targetFiles: '**/*.yaml'
      tokenPattern: rm
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      Contents: >-
        k8s-secret.yaml

        k8s-azure-flask-app.yaml
      TargetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
...
