---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_HOST:ZXBtLXJzLXNxMDEucG9zdGdyZXMuZGF0YWJhc2UuYXp1cmUuY29t
  DB_USER:b2RtaW5AZXBtLXJzLXNxMDE= 
  DB_PASSWORD:a2xheGRoc2ZsYXNkaDk4NzI2MzQ5MTgzMjc0XiVeJiQl
  DB_NAME:d2VhdGhlcg==