kind: Namespace
apiVersion: v1
metadata:
  name: __NAMESPACE__
  labels:
    name: __NAMESPACE__
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-flask-app
  namespace: __NAMESPACE__
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azure-flask-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: azure-flask-app
    spec:
      containers:
      - name: azure-flask-app
        image: rsepamacr.azurecr.io/rinxster:__Build.BuildId__
        ports:
        - containerPort: 80
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m" 
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_NAME              

---
apiVersion: v1
kind: Service
metadata:
  name: azure-flask-app
  namespace: __NAMESPACE__
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: __NAMESPACE__-epm-diploma-v7
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-flask-app

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-hpa
  namespace: __NAMESPACE__
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: azure-flask-app
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
