apiVersion: v1
kind: Service
metadata:
    name: "rsepamk8s-e0b6"
    labels:
        app: "rsepamk8s-e0b6"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "rsepamk8s-e0b6"